---
- hosts: all
  sudo: yes
  remote_user: root
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - build-essential
        - git-core
        - curl
        - sqlite3
        - libsqlite3-dev
        - libxml2-dev
        - libxslt1-dev
        - libreadline-dev
        - libyaml-dev
        - libcurl4-openssl-dev
        - libncurses5-dev
        - libgdbm-dev
        - libffi-dev
        - runit
        - postgresql
        - libpq-dev
        - nodejs
        - htop
        - python-psycopg2
        - memcached

    - name: Create user
      user:
        name: deployer
        createhome: yes
        shell: /bin/bash
        group: root
        generate_ssh_key: yes

    - name: Copy my ssh key
      authorized_key:
        key: "{{ lookup('file', key_path) }}"
        user: "deployer"
        state: present

    - name: Create user for postgres
      sudo: yes
      sudo_user: postgres
      postgresql_user:
        name: "{{ app_name }}"
        password: "{{ db_password }}"
        role_attr_flags: CREATEDB

- name: Install ruby with rvm
  hosts: all
  vars:
    rvm1_install_flags: '--auto-dotfiles --user-install'
  roles:
    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }

- name: Install redis
  hosts: all
  roles:
    - DavidWittman.redis

- name: Install nginx
  hosts: all
  roles:
    - role: jdauphant.nginx
      nginx_configs:
        upstream:
          - "upstream {{ app_name }}
              { server unix:/tmp/unicorn_{{ app_name }}.sock fail_timeout=0;
            }"
      nginx_sites:
        #change it to your app name
        app_name:
          - "client_max_body_size 4G"
          - "server_name {{ server_name }}"
          - "keepalive_timeout 5"
          - "root /var/www/{{ app_name }}/current/public"
          - "location ~ ^/(assets)/  {
              root /var/www/{{ app_name }}/current/public;
              index index.html;
              gzip_static on;
              expires max; add_header Cache-Control public;
            }"
          - "location / {
              if (-f $document_root/system/maintenance.html) {
                return 503;
              }
              try_files $uri @app;
            }"
          - "error_page 503 @maintenance"
          - "location @maintenance {
              rewrite ^(.*)$ /system/maintenance.html break;
             }"
          - "location @app {
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Host $http_host;
              proxy_redirect off;
              proxy_pass http://{{ app_name }};
            }"
