---
- hosts: all
  sudo: yes
  remote_user: root
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - build-essential
        - git-core
        - curl
        - sqlite3
        - libsqlite3-dev
        - libxml2-dev
        - libxslt1-dev
        - libreadline-dev
        - libyaml-dev
        - libcurl4-openssl-dev
        - libncurses5-dev
        - libgdbm-dev
        - libffi-dev
        - runit
        - postgresql
        - libpq-dev
        - nodejs
        - htop
        - python-psycopg2

    - name: Create user
      user:
        name: deployer
        createhome: yes
        shell: /bin/bash
        groups: root
        generate_ssh_key: yes

    - name: Copy my ssh key
      authorized_key:
        key: "{{ lookup('file', '/Users/vorob/.ssh/github_id.pub') }}"
        user: "deployer"
        state: present

    - name: Create user for postgres
      sudo: yes
      sudo_user: postgres
      postgresql_user: name=deployer password=qweqweqwe role_attr_flags=CREATEDB

- name: Install ruby with rvm
  hosts: all
  vars:
    rvm1_install_flags: '--auto-dotfiles --user-install'
  roles:
    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }

- name: Install redis
  hosts: all
  vars:
    redis_user: deployer
  roles:
    - DavidWittman.redis

- name: Install nginx
  hosts: all
  roles:
    - jdauphant.nginx
